import { useEffect, useState } from 'react'
import './App.css'
import './sections.css'
import './responsive.css'
import './branding.css'
import './theme.css'

const navItems = ['Home', 'Check-In', 'Today', 'Resources', 'Professionals', 'About']

function ArrowIcon() { return <svg viewBox="0 0 24 24" aria-hidden="true"><path d="M5 12h13M13 6l6 6-6 6" /></svg> }
function ThemeToggle({ theme, onToggle }) { const isDark = theme === 'dark'; return <button className="theme-toggle" type="button" onClick={onToggle} aria-label={`Switch to ${isDark ? 'light' : 'dark'} mode`} title={`Switch to ${isDark ? 'light' : 'dark'} mode`}><svg className="sun-icon" viewBox="0 0 24 24" aria-hidden="true"><circle cx="12" cy="12" r="3.5" /><path d="M12 2v2.2M12 19.8V22M4.93 4.93l1.56 1.56M17.51 17.51l1.56 1.56M2 12h2.2M19.8 12H22M4.93 19.07l1.56-1.56M17.51 6.49l1.56-1.56" /></svg><svg className="moon-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M20.4 14.6A8.5 8.5 0 0 1 9.4 3.6 8.5 8.5 0 1 0 20.4 14.6Z" /></svg><span className="theme-knob" /></button> }
function BrandLogo({ footer = false }) { return <a className={footer ? 'brand-logo brand-logo-footer' : 'brand-logo'} href="#home"><img src="/logo-transparent.png" alt="Medixony" /></a> }

function LivingCanvas() {
  return <div className="living-canvas" aria-label="An illustration of the different parts of everyday well-being" role="img">
    <span className="canvas-sun" /><span className="canvas-cloud cloud-one" /><span className="canvas-cloud cloud-two" /><span className="canvas-orb orb-one" /><span className="canvas-orb orb-two" /><span className="canvas-line line-one" /><span className="canvas-line line-two" />
    <div className="canvas-card card-home"><span className="icon-moon">☾</span><b>Sleep</b><small>your rhythm</small></div><div className="canvas-card card-rest"><span className="icon-mind">✦</span><b>Mood</b><small>your inner weather</small></div><div className="canvas-card card-people"><span className="icon-people">● ●</span><b>Connection</b><small>your circle</small></div><div className="canvas-card card-mind"><span className="icon-house">⌁</span><b>Focus</b><small>your attention</small></div><div className="canvas-card card-energy"><span>↗</span><b>Energy</b><small>your pace</small></div>
    <div className="canvas-you"><span>YOU</span><small>at the centre</small></div><div className="plant"><span className="stem" /><i className="leaf leaf-a" /><i className="leaf leaf-b" /><i className="leaf leaf-c" /><i className="leaf leaf-d" /></div><div className="canvas-caption"><span>well-being is a living picture</span><ArrowIcon /></div>
  </div>
}

function TodayPreview() { return <section className="today-preview section" id="resources"><div className="section-intro"><p className="eyebrow">A future daily rhythm</p><h2>A little support<br />for <em>today.</em></h2><p>A gentle, visual preview of a future Medixony experience—built around the day you actually have.</p></div><article className="today-card"><div className="today-card-top"><span className="today-label">Today</span><span className="today-date">Tuesday · 10:24</span></div><h3>Good morning.</h3><p>“Your energy seems a little lower today. Let’s keep things gentle.”</p><div className="today-meters">{[['Energy', 3], ['Mood', 4], ['Focus', 2]].map(([label, active]) => <div key={label}><span>{label}</span><i>{[1, 2, 3, 4, 5].map(level => <b className={level <= active ? 'is-active' : ''} key={level} />)}</i></div>)}</div><div className="today-suggestion"><span>Suggested next step</span><strong>Take 10 quiet minutes before your next task.</strong></div><button type="button" className="button button-primary">Explore today’s support <ArrowIcon /></button></article></section> }

function CheckInPlaceholder() { return <main className="placeholder-page"><a href="/" className="brand-logo"><img src="/logo-transparent.png" alt="Medixony" /></a><div><p className="eyebrow">A gentle beginning</p><h1>Your check-in will live here.</h1><p>We’re shaping this experience with care. For now, you can return to explore Medixony.</p><a className="button button-primary" href="/">Back to home <ArrowIcon /></a></div></main> }

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [theme, setTheme] = useState(() => localStorage.getItem('medixony-theme') || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light'))
  useEffect(() => { document.documentElement.dataset.theme = theme; localStorage.setItem('medixony-theme', theme) }, [theme])
  if (window.location.pathname === '/check-in') return <CheckInPlaceholder />
  return <div className="site-shell">
    <header className="topbar"><BrandLogo /><nav className={menuOpen ? 'main-nav is-open' : 'main-nav'} aria-label="Main navigation">{navItems.map((item) => <a key={item} href={item === 'Home' ? '#home' : item === 'Check-In' ? '/check-in' : `#${item.toLowerCase()}`} onClick={() => setMenuOpen(false)}>{item}</a>)}<div className="mobile-utility"><a href="#privacy">Privacy</a><a href="#footer">Help</a></div></nav><div className="topbar-actions"><a href="#privacy">Privacy</a><a href="#footer">Help</a><a className="button button-small" href="/check-in">Start Check-In <ArrowIcon /></a></div><ThemeToggle theme={theme} onToggle={() => setTheme(theme === 'dark' ? 'light' : 'dark')} /><button className="menu-toggle" type="button" aria-label="Toggle menu" aria-expanded={menuOpen} onClick={() => setMenuOpen(!menuOpen)}><span /><span /></button></header>
    <main>
      <section className="hero section" id="home"><div className="hero-copy reveal"><p className="eyebrow">A quieter kind of support</p><h1>How are you,<br /><em>really?</em></h1><p className="hero-text">A simple, private way to understand your well-being and discover small steps that may help you feel better.</p><div className="hero-actions"><a className="button button-primary" href="/check-in">Start My Check-In <ArrowIcon /></a><a className="text-link" href="#how-it-works">How Medixony Works <ArrowIcon /></a></div><p className="personal-signal"><span>✦</span> Designed around your life, not a label.</p><p className="hero-note">Private, thoughtful, and entirely at your pace.</p></div><LivingCanvas /></section>
      <section className="context section" id="about"><div className="section-intro reveal"><p className="eyebrow">There’s more to the story</p><h2>Real life doesn’t fit<br />into <em>categories.</em></h2></div><div className="context-body"><p>Maybe sleep has been off. Your thoughts keep spinning. You feel distant from people, unmotivated, or the weight of academic pressure is catching up.</p><p>Sometimes you know something is hard, but not what label belongs to it.</p><div className="context-panels"><div className="traditional-panel"><span>Traditional approach</span><b>Anxiety</b><b>Depression</b><b>Stress</b><b>Sleep</b></div><div className="medixony-panel"><span>Medixony</span><b>What’s happening?</b><i>↓</i><b>What’s affecting it?</b><i>↓</i><b>What can help today?</b></div></div><div className="question-shift"><div><span>Instead of asking</span><strong>“What’s wrong with you?”</strong></div><ArrowIcon /><div className="active"><span>We begin with</span><strong>“What’s going on?”</strong></div></div></div></section>
      <section className="context-first section" id="today"><div className="section-intro"><p className="eyebrow">A fuller picture</p><h2>Context-first<br /><em>well-being.</em></h2><p>Medixony considers the parts of life around how you feel—then helps identify one realistic next step.</p></div><div className="factors"><div className="factor-grid">{['Context', 'Emotional state', 'Lifestyle', 'Available time', 'Budget', 'Personal preference'].map((factor, index) => <div className={`factor factor-${index + 1}`} key={factor}><span>0{index + 1}</span>{factor}</div>)}</div><div className="pathway"><span>Life</span><i /><span>Need</span><i /><span className="pathway-action">Action <ArrowIcon /></span></div></div></section>
      <TodayPreview />
      <section className="how section" id="how-it-works"><div className="section-heading"><div><p className="eyebrow">A path that learns with you</p><h2>How Medixony<br /><em>works.</em></h2></div><p>Not a one-size-fits-all plan. Just a respectful way forward, one check-in at a time.</p></div><div className="steps">{[['01', 'Understand', 'What is happening?'], ['02', 'Act', 'What can I realistically do?'], ['03', 'Reflect', 'Did it help?'], ['04', 'Adapt', 'What should Medixony recommend next time?']].map(([number, title, text], index) => <article className="step-card" key={title}><span className="step-number">{number}</span><span className="step-line" /><h3>{title}</h3><p>{text}</p>{index === 3 && <span className="step-spark">✦</span>}</article>)}</div></section>
      <section className="trust section" id="privacy"><div className="trust-mark" aria-hidden="true">✦</div><div><p className="eyebrow">Your story is yours</p><h2>Private by <em>design.</em></h2><p className="trust-copy">Support works best when it feels safe. We’re building Medixony around clarity, choice, and practical care.</p></div><ul>{['No forced diagnosis', 'Clear consent', 'Privacy-conscious design', 'Practical support', 'Professional support when appropriate'].map(item => <li key={item}><span>✓</span>{item}</li>)}</ul></section>
      <section className="professionals section" id="professionals"><div className="section-heading"><div><p className="eyebrow">When support needs a human</p><h2>Sometimes a small step is enough.<br /><em>Sometimes you need a person.</em></h2></div><p>When the time is right, Medixony will make it easier to find the kind of professional support that fits.</p></div><div className="support-cards">{[['◌', 'Psychologist Chat', 'A calm space for a conversation.'], ['◐', 'First Video Session', 'Meet from wherever you feel comfortable.'], ['✣', 'Professional Support', 'Guidance when you want a little more.']].map(([icon, title, text]) => <article className="support-card" key={title}><span className="support-icon">{icon}</span><span className="coming-soon">Coming soon</span><h3>{title}</h3><p>{text}</p><span className="card-arrow"><ArrowIcon /></span></article>)}</div></section>
    </main>
    <footer id="footer"><div className="footer-top"><div className="footer-brand"><BrandLogo footer /><p>Understand yourself.<br />Care for yourself.</p></div><div className="footer-links"><div><h4>Product</h4><a href="/check-in">Check-In</a><a href="#today">Today</a><a href="#resources">Resources</a><a href="#professionals">Professionals</a></div><div><h4>Company</h4><a href="#about">About</a><a href="#privacy">Privacy</a><a href="#footer">Terms</a></div><div><h4>Support</h4><a href="#footer">Help</a><a href="#footer">Safety</a></div></div></div><div className="footer-bottom"><p>Medixony is a well-being support tool and does not diagnose mental health conditions.</p><span>© 2026 Medixony</span></div></footer>
  </div>
}
export default App
